@echo off
REM ===================================================================
REM  Auto-start PocketBase every time the current user logs in.
REM  Uses the user's Startup folder - no admin privileges required.
REM
REM  Creates:  %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\
REM              MATAM_PocketBase.cmd    (calls start_pocketbase.cmd, hidden)
REM
REM  To remove: disable_autostart.cmd
REM ===================================================================
setlocal
cd /d "%~dp0"

set "TARGET_SCRIPT=%~dp0start_pocketbase.cmd"
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "STUB=%STARTUP%\MATAM_PocketBase.cmd"
set "QUIET=%~1"

if not exist "%TARGET_SCRIPT%" (
    if /I NOT "%QUIET%"=="quiet" (
        echo [ERROR] start_pocketbase.cmd not found next to this script.
        pause
    )
    exit /b 1
)

if not exist "%STARTUP%" (
    if /I NOT "%QUIET%"=="quiet" (
        echo [ERROR] Startup folder not found at %STARTUP%
        pause
    )
    exit /b 1
)

REM Write a tiny stub that launches the real script minimized
(
    echo @echo off
    echo REM Auto-generated by enable_autostart.cmd - do not edit
    echo start "" /min "%TARGET_SCRIPT%"
) > "%STUB%"

if not exist "%STUB%" (
    if /I NOT "%QUIET%"=="quiet" (
        echo [ERROR] Failed to write %STUB%
        pause
    )
    exit /b 2
)

if /I NOT "%QUIET%"=="quiet" (
    echo.
    echo Auto-start registered.
    echo   Startup entry : %STUB%
    echo   Will launch   : %TARGET_SCRIPT%  (minimized^)
    echo.
    echo To disable later, run:   disable_autostart.cmd
    echo.
    pause
)
endlocal
